### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ririko5834** [Notavone/discord-panel#39]
When i paste token into popup i am getting error:
![image](https://user-images.githubusercontent.com/64729293/99179917-22bb3e80-2722-11eb-8f07-cea44eb74b10.png)
I provided valid token (it works in my discord.js bot)

+ i am getting that client and locales  are not defined in panel.js
![image](https://user-images.githubusercontent.com/64729293/99179942-4a120b80-2722-11eb-8d01-2ad048ad17ff.png)
![image](https://user-images.githubusercontent.com/64729293/99179946-58f8be00-2722-11eb-9ed8-eb115c1e5d67.png)

**Comment by Notavone** [comment]
they are not found because they are not imported but since the index.html uses scripts in this order
- main.js
- panel.js
they can be found when loading the panel
I will work on the "token not found" problem when I have enough time to
I'm currently working on other projects and a redesign of this one

**Comment by ririko5834** [comment]
ok

**Comment by Notavone** [comment]
should be fixed by the latest version
